
package View;

import java.awt.Dimension;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JPanel;


public class View_Login extends javax.swing.JFrame {

   private int x,y;
    public View_Login() {
        initComponents();
        
        //Agrega un fondo al frame
        ((JPanel)getContentPane()).setOpaque(false); 
        ImageIcon uno=new ImageIcon(this.getClass().getResource("/Imagenes/FondoLogin.png")); 
        JLabel fondo= new JLabel(); 
        fondo.setIcon(uno); 
        getLayeredPane().add(fondo,JLayeredPane.FRAME_CONTENT_LAYER);
        fondo.setBounds(0,0,uno.getIconWidth(),uno.getIconHeight());
        
        //Agrega un icono al frame
        setIconImage(new ImageIcon(this.getClass().getResource("/Imagenes/Icono.png")).getImage());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblContrasena = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblImagen = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        psContrasena = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        lblIngresar = new javax.swing.JLabel();
        lblMover = new javax.swing.JLabel();
        lblMinizar = new javax.swing.JLabel();
        lblSalir = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 449));
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(790, 339));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblContrasena.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        lblContrasena.setText("CONTRASEÑA");
        jPanel1.add(lblContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 150, 30));

        lblUsuario.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        lblUsuario.setText("USUARIO");
        jPanel1.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 140, 30));

        lblImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Login.png"))); // NOI18N
        jPanel1.add(lblImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 250, 240));

        txtUsuario.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        txtUsuario.setText("USUARIO");
        txtUsuario.setBorder(null);
        txtUsuario.setOpaque(false);
        jPanel1.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 260, 170, 30));

        psContrasena.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        psContrasena.setText("CONTRASEÑA");
        psContrasena.setBorder(null);
        psContrasena.setOpaque(false);
        jPanel1.add(psContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 310, 190, 30));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, 180, 10));

        lblIngresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Comenzar.png"))); // NOI18N
        lblIngresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(lblIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 270, -1, -1));

        lblMover.setText(" ");
        lblMover.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        jPanel1.add(lblMover, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 730, 30));

        lblMinizar.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        lblMinizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMinizar.setText("-");
        lblMinizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(lblMinizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 0, 40, 30));

        lblSalir.setFont(new java.awt.Font("Snap ITC", 0, 24)); // NOI18N
        lblSalir.setForeground(new java.awt.Color(255, 0, 0));
        lblSalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSalir.setText("X");
        lblSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(lblSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(761, 0, 40, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblContrasena;
    private javax.swing.JLabel lblImagen;
    public javax.swing.JLabel lblIngresar;
    public javax.swing.JLabel lblMinizar;
    public javax.swing.JLabel lblMover;
    public javax.swing.JLabel lblSalir;
    private javax.swing.JLabel lblUsuario;
    public javax.swing.JPasswordField psContrasena;
    public javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
